#!/bin/python3
"A Pythagorean triplet is a set of three natural numbers,a<b<c , for which,
a^2+b^2=c^2
For example,  362+4^2=4^2

Given ,N Check if there exists any Pythagorean triplet for which a+b+c=N
Find maximum possible value of abc among all such Pythagorean triplets, If there is no such Pythagorean triplet print -1 ."

---------------------
Code:1
a=int(input())
lis=[]
for _ in range(a):
    lis.append(int(input()))
#print(lis)
lis3=[]
for t in lis:
    lis2=[]
    for i in range(1,t+1):
        j=2
        while j<i:
            if i%j==0:
                break
            j+=1    
        else:
            lis2.append(i)
    lis3.append(lis2)        

  
lis4=[]
for i in lis3:
    
    lis4.append(sum(i)-1)
print( *lis4,sep='\n')


