#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'weightedMean' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY X
#  2. INTEGER_ARRAY W
#

def weightedMean(X, W):
    lis=[]
    for i in range(len(X)):
        lis.append(X[i]* W[i])
    p=sum(lis) / sum(W)
    print(round(p,1))

if __name__ == '__main__':
    n = int(input().strip())

    vals = list(map(int, input().rstrip().split()))

    weights = list(map(int, input().rstrip().split()))

    weightedMean(vals, weights)
-----------------------------------------------------------------

Inputs:5 ..size of array
10 40 30 50 20 .. elements in array
1 2 3 4 5.. elements in array
