#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'stdDev' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def stdDev(arr):
          
        mean=sum(arr)/len(arr)
        
        lis=[]
        for i in range(len(arr)):
            lis.append((arr[i]-mean)**2)
        print(round((sum(lis)/len(arr))**0.5,1))
            
           
if __name__ == '__main__':
    n = int(input().strip())

    vals = list(map(int, input().rstrip().split()))

    stdDev(vals)
----------------------------------
5
10 40 30 50 20
